export default [
    {
        files: ["**/*.js"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                fetch: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                location: "readonly",
                history: "readonly",
                navigator: "readonly",
                FormData: "readonly",
                alert: "readonly",
                confirm: "readonly",
                prompt: "readonly",
                Event: "readonly",
                CustomEvent: "readonly",
                HTMLElement: "readonly",
                HTMLFormElement: "readonly",
                HTMLInputElement: "readonly",
                HTMLButtonElement: "readonly",
                HTMLSelectElement: "readonly",
                HTMLCanvasElement: "readonly",
                Image: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                Blob: "readonly",
                File: "readonly",
                FileReader: "readonly",
                Request: "readonly",
                Response: "readonly",
                Headers: "readonly",
                AbortController: "readonly",
                TextDecoder: "readonly",
                TextEncoder: "readonly",
                crypto: "readonly",
                indexedDB: "readonly",
                performance: "readonly",
                screen: "readonly",
                requestAnimationFrame: "readonly",
                getComputedStyle: "readonly",
                Node: "readonly",
                CSS: "readonly",
                L: "readonly",
                Chart: "readonly"
            }
        },
        rules: {
            "no-unused-vars": "warn",
            "no-undef": "error",
            "no-console": "off",
            "no-debugger": "warn"
        }
    }
];